//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public AppUser()
        {
            this.AppUser1 = new HashSet<AppUser>();
            this.Clients = new HashSet<Client>();
            this.ClientAdresses = new HashSet<ClientAdress>();
            this.ClientVisits = new HashSet<ClientVisit>();
            this.ClientVisits1 = new HashSet<ClientVisit>();
            this.ClientVisits2 = new HashSet<ClientVisit>();
            this.Contacts = new HashSet<Contact>();
            this.ContactAdresses = new HashSet<ContactAdress>();
            this.Contracts = new HashSet<Contract>();
            this.Contracts1 = new HashSet<Contract>();
            this.Contracts2 = new HashSet<Contract>();
            this.ContractPayments = new HashSet<ContractPayment>();
            this.ContractSections = new HashSet<ContractSection>();
            this.ContractTimeInfoes = new HashSet<ContractTimeInfo>();
            this.Locations = new HashSet<Location>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
            this.ClientEquipments = new HashSet<ClientEquipment>();
            this.ProductInventories = new HashSet<ProductInventory>();
            this.ProductListPriceHistories = new HashSet<ProductListPriceHistory>();
            this.ProductModels = new HashSet<ProductModel>();
            this.ProductModelProductDescriptionCultures = new HashSet<ProductModelProductDescriptionCulture>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string LastName1 { get; set; }
        public string LastName2 { get; set; }
        public bool IsActive { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedUserId { get; set; }
    
        public virtual ICollection<AppUser> AppUser1 { get; set; }
        public virtual AppUser AppUser2 { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<ClientAdress> ClientAdresses { get; set; }
        public virtual ICollection<ClientVisit> ClientVisits { get; set; }
        public virtual ICollection<ClientVisit> ClientVisits1 { get; set; }
        public virtual ICollection<ClientVisit> ClientVisits2 { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<ContactAdress> ContactAdresses { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<Contract> Contracts1 { get; set; }
        public virtual ICollection<Contract> Contracts2 { get; set; }
        public virtual ICollection<ContractPayment> ContractPayments { get; set; }
        public virtual ICollection<ContractSection> ContractSections { get; set; }
        public virtual ICollection<ContractTimeInfo> ContractTimeInfoes { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual ICollection<ClientEquipment> ClientEquipments { get; set; }
        public virtual ICollection<ProductInventory> ProductInventories { get; set; }
        public virtual ICollection<ProductListPriceHistory> ProductListPriceHistories { get; set; }
        public virtual ICollection<ProductModel> ProductModels { get; set; }
        public virtual ICollection<ProductModelProductDescriptionCulture> ProductModelProductDescriptionCultures { get; set; }
    }
}
