//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientEquipment
    {
        public int ProductId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedUserId { get; set; }
        public string Description { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Client Client { get; set; }
        public virtual ClientAdress ClientAdress { get; set; }
        public virtual Product Product { get; set; }
    }
}
