//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientVisit
    {
        public int VisitId { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime DeathlineDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> ClientAdressId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public int DesignatedUserId { get; set; }
        public int CreateUserId { get; set; }
        public int ModifiedUserId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual AppUser AppUser2 { get; set; }
        public virtual Client Client { get; set; }
        public virtual ClientAdress ClientAdress { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
