//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.ClientAdresses = new HashSet<ClientAdress>();
            this.ClientEquipments = new HashSet<ClientEquipment>();
            this.ClientVisits = new HashSet<ClientVisit>();
            this.Contacts = new HashSet<Contact>();
            this.Contracts = new HashSet<Contract>();
            this.Orders = new HashSet<Order>();
        }
    
        public int ClientId { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Phone { get; set; }
        public string Movil { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<int> ClientTypeId { get; set; }
        public string CIF { get; set; }
        public string Observations { get; set; }
        public string WebSite { get; set; }
        public Nullable<bool> Verified { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ModifiedUserId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual ICollection<ClientAdress> ClientAdresses { get; set; }
        public virtual ClientType ClientType { get; set; }
        public virtual ICollection<ClientEquipment> ClientEquipments { get; set; }
        public virtual ICollection<ClientVisit> ClientVisits { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
