//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractType
    {
        public ContractType()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int ContractTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
