//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractPayment
    {
        public int ContractId { get; set; }
        public string PaymentNumber { get; set; }
        public int PaymentTypeId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string Observations { get; set; }
        public int ModifiedUserId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
