//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.ClientVisits = new HashSet<ClientVisit>();
            this.ContactAdresses = new HashSet<ContactAdress>();
            this.Contracts = new HashSet<Contract>();
            this.Orders = new HashSet<Order>();
        }
    
        public int ContactId { get; set; }
        public string Name { get; set; }
        public string Nickname { get; set; }
        public string FirstLastName { get; set; }
        public string SecondLastName { get; set; }
        public string Phone { get; set; }
        public string Movil { get; set; }
        public string Fax { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public string Description { get; set; }
        public string Position { get; set; }
        public int ClientId { get; set; }
        public int ClientAdressId { get; set; }
        public Nullable<int> DepartamentId { get; set; }
        public int ContactTypeId { get; set; }
        public int GenreId { get; set; }
        public Nullable<int> SocialStateId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedUserId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Client Client { get; set; }
        public virtual ClientAdress ClientAdress { get; set; }
        public virtual ICollection<ClientVisit> ClientVisits { get; set; }
        public virtual ContactType ContactType { get; set; }
        public virtual Departament Departament { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual SocialState SocialState { get; set; }
        public virtual ICollection<ContactAdress> ContactAdresses { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
