//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractSection
    {
        public ContractSection()
        {
            this.ContractSection1 = new HashSet<ContractSection>();
        }
    
        public int ContractSectionId { get; set; }
        public int ContractSectionTypeId { get; set; }
        public string Content { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedUserId { get; set; }
        public int ContractId { get; set; }
        public int ParentSectionId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual ICollection<ContractSection> ContractSection1 { get; set; }
        public virtual ContractSection ContractSection2 { get; set; }
    }
}
