//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.ContractSections = new HashSet<ContractSection>();
            this.Orders = new HashSet<Order>();
        }
    
        public int ContractId { get; set; }
        public string Name { get; set; }
        public int ContractTypeId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public string AdditionalInformation { get; set; }
        public byte[] ClientSignature { get; set; }
        public byte[] RepresentativeSignature { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int RepresentativeUserId { get; set; }
        public int CreateUserId { get; set; }
        public int ModifiedUserId { get; set; }
        public string ReferenceNumber { get; set; }
        public int ContractStateId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual AppUser AppUser2 { get; set; }
        public virtual Client Client { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual ContractState ContractState { get; set; }
        public virtual ContractType ContractType { get; set; }
        public virtual ContractPayment ContractPayment { get; set; }
        public virtual ICollection<ContractSection> ContractSections { get; set; }
        public virtual ContractTimeInfo ContractTimeInfo { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
