//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractTimeInfo
    {
        public int ContractId { get; set; }
        public System.DateTime StartingDate { get; set; }
        public System.DateTime DeathlineDate { get; set; }
        public System.DateTime CompletedDate { get; set; }
        public System.DateTime RealStartDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedUserId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
