//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactAdress
    {
        public int AdressId { get; set; }
        public string Name { get; set; }
        public string AdressText { get; set; }
        public string City { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public int AdressTypeId { get; set; }
        public string Description { get; set; }
        public int ContactId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedUser { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
