//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.ClientAdresses = new HashSet<ClientAdress>();
            this.Locations = new HashSet<Location>();
            this.Provinces = new HashSet<Province>();
        }
    
        public int CountryId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<ClientAdress> ClientAdresses { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Province> Provinces { get; set; }
    }
}
