//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SERMANEntities : DbContext
    {
        public SERMANEntities()
            : base("name=SERMANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdressType> AdressTypes { get; set; }
        public DbSet<AppUser> AppUsers { get; set; }
        public DbSet<BusinessUnit> BusinessUnits { get; set; }
        public DbSet<CargoRegion> CargoRegions { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<ClientAdress> ClientAdresses { get; set; }
        public DbSet<ClientEquipment> ClientEquipments { get; set; }
        public DbSet<ClientType> ClientTypes { get; set; }
        public DbSet<ClientVisit> ClientVisits { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<ContactAdress> ContactAdresses { get; set; }
        public DbSet<ContactType> ContactTypes { get; set; }
        public DbSet<Contract> Contracts { get; set; }
        public DbSet<ContractPayment> ContractPayments { get; set; }
        public DbSet<ContractSection> ContractSections { get; set; }
        public DbSet<ContractSectionType> ContractSectionTypes { get; set; }
        public DbSet<ContractState> ContractStates { get; set; }
        public DbSet<ContractTimeInfo> ContractTimeInfoes { get; set; }
        public DbSet<ContractType> ContractTypes { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Culture> Cultures { get; set; }
        public DbSet<Departament> Departaments { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<GeographicZone> GeographicZones { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<Mark> Marks { get; set; }
        public DbSet<Model> Models { get; set; }
        public DbSet<OffertState> OffertStates { get; set; }
        public DbSet<OffertType> OffertTypes { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderConcept> OrderConcepts { get; set; }
        public DbSet<OrderProduct> OrderProducts { get; set; }
        public DbSet<OrderState> OrderStates { get; set; }
        public DbSet<PaymentType> PaymentTypes { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }
        public DbSet<ProductCostHistory> ProductCostHistories { get; set; }
        public DbSet<ProductDescription> ProductDescriptions { get; set; }
        public DbSet<ProductInventory> ProductInventories { get; set; }
        public DbSet<ProductListPriceHistory> ProductListPriceHistories { get; set; }
        public DbSet<ProductModel> ProductModels { get; set; }
        public DbSet<ProductModelProductDescriptionCulture> ProductModelProductDescriptionCultures { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<Result> Results { get; set; }
        public DbSet<SocialState> SocialStates { get; set; }
        public DbSet<StagesState> StagesStates { get; set; }
        public DbSet<TaskState> TaskStates { get; set; }
        public DbSet<Title> Titles { get; set; }
        public DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
        public DbSet<VisitState> VisitStates { get; set; }
        public DbSet<WorkSheetType> WorkSheetTypes { get; set; }
    }
}
