//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int OrderId { get; set; }
        public string Title { get; set; }
        public string OrderNumber { get; set; }
        public int ManagerId { get; set; }
        public Nullable<System.DateTime> InitialDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public int ClientAdressId { get; set; }
        public int OrderStateId { get; set; }
        public Nullable<bool> Verified { get; set; }
        public int ConceptId { get; set; }
        public string Description { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedUserId { get; set; }
        public Nullable<int> ContractId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual Client Client { get; set; }
        public virtual ClientAdress ClientAdress { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual OrderConcept OrderConcept { get; set; }
        public virtual OrderState OrderState { get; set; }
    }
}
