//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ClientEquipments = new HashSet<ClientEquipment>();
            this.OrderProducts = new HashSet<OrderProduct>();
            this.ProductInventories = new HashSet<ProductInventory>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public string ProductNumber { get; set; }
        public int ProductModelId { get; set; }
    
        public virtual ICollection<ClientEquipment> ClientEquipments { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductModel ProductModel { get; set; }
        public virtual ICollection<ProductInventory> ProductInventories { get; set; }
        public virtual ProductListPriceHistory ProductListPriceHistory { get; set; }
    }
}
