//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductModel
    {
        public ProductModel()
        {
            this.Products = new HashSet<Product>();
            this.ProductModelProductDescriptionCultures = new HashSet<ProductModelProductDescriptionCulture>();
        }
    
        public int ProductModelId { get; set; }
        public string Name { get; set; }
        public string ModelNumber { get; set; }
        public int CategoryId { get; set; }
        public string Size { get; set; }
        public Nullable<int> SizeUoMId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> WeightUoMId { get; set; }
        public Nullable<int> MarkId { get; set; }
        public Nullable<decimal> StandarCost { get; set; }
        public Nullable<decimal> ListPriceCost { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> VolumeUoMId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedUserId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Mark Mark { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure1 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure2 { get; set; }
        public virtual ICollection<ProductModelProductDescriptionCulture> ProductModelProductDescriptionCultures { get; set; }
    }
}
