//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasure
    {
        public UnitOfMeasure()
        {
            this.ProductModels = new HashSet<ProductModel>();
            this.ProductModels1 = new HashSet<ProductModel>();
            this.ProductModels2 = new HashSet<ProductModel>();
        }
    
        public int UoMId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProductModel> ProductModels { get; set; }
        public virtual ICollection<ProductModel> ProductModels1 { get; set; }
        public virtual ICollection<ProductModel> ProductModels2 { get; set; }
    }
}
