//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igneel.Assets.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder
    {
        public Folder()
        {
            this.Folder1 = new HashSet<Folder>();
            this.Resources = new HashSet<Resource>();
            this.ResourceTypes = new HashSet<ResourceType>();
        }
    
        public int FolderId { get; set; }
        public string Name { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public int CreateUserId { get; set; }
        public int UpdateUserId { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<Folder> Folder1 { get; set; }
        public virtual Folder Folder2 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Resource> Resources { get; set; }
        public virtual ICollection<ResourceType> ResourceTypes { get; set; }
    }
}
