//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igneel.Assets.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.SceneResources = new HashSet<SceneResource>();
            this.SceneResources1 = new HashSet<SceneResource>();
            this.SceneResources2 = new HashSet<SceneResource>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ResourceTypeId { get; set; }
        public int FolderId { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Folder Folder { get; set; }
        public virtual User User { get; set; }
        public virtual ResourceType ResourceType { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<SceneResource> SceneResources { get; set; }
        public virtual ICollection<SceneResource> SceneResources1 { get; set; }
        public virtual ICollection<SceneResource> SceneResources2 { get; set; }
    }
}
