//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Igneel.Assets.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Folders = new HashSet<Folder>();
            this.Folders1 = new HashSet<Folder>();
            this.Resources = new HashSet<Resource>();
            this.Resources1 = new HashSet<Resource>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<Folder> Folders { get; set; }
        public virtual ICollection<Folder> Folders1 { get; set; }
        public virtual ICollection<Resource> Resources { get; set; }
        public virtual ICollection<Resource> Resources1 { get; set; }
    }
}
